### ISSUE TITLE
Should I merge the assemblying repo to this repo?

### ISSUE THREAD

**Issue by leoisl** [iqbal-lab-org/AllTheBacteria#2]
I have a (still private) repo that I am using to assemble the remaining 1.3kk. It is a bit simple, it has just a small snakemake pipeline to do the assembly, and a few input wrangling scripts and utility pipelines. Just wondering if I can/should continue developing on it, or if I should merge it into this repo, and resume development here

**Comment by iqbal-lab** [comment]
I dont think it matters much, could finish what you're doing and then merge over here?

**Comment by leoisl** [comment]
Ok, thanks!

**Comment by mbhall88** [comment]
What's the status on this. I just realised there is no code on this repo for reproducing any of the pipeline steps for ATB.

**Comment by leoisl** [comment]
Assembly pipeline is here: https://github.com/leoisl/bacterial_assembly_pipeline but lacks proper documentation, tests, needs refactoring, etc etc

**Comment by mbhall88** [comment]
Okay, might be worth at least linking to that pipeline from the main repo? Or is there a plan to port it to here?
